;GROUP 71
;PROBLEM 23

.MODEL TINY
.DATA


;8253 USED TO GENERATE CLOCK FOR ADC
CNT0 EQU 20H
CREG EQU 26H


;8255(1)  INITIALISE
PORT1A EQU 00H 	;CONTROLLING THE LCD
PORT1B EQU 02H 	;INPUT TO LCD
PORT1C EQU 04H 	;UPPER - ROW
		        ;LOWER - COLUMN
CREG1 EQU 06H


;8255(2) USED FOR ADC

PORT2A EQU 10H 	;INPUT TO DI DEVICE
PORT2B EQU 12H 	;ADC
PORT2C EQU 14H 	;PC1 - SOC OF ADC
;PC3 - ADDC OF ADC (USED FOR SELECTING THE ;FIRST & SECOND INPUT CHANNEL OF ADC)
;PC5 - EOC OF ADC
CREG2 EQU 16H

temp_range db 10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40

humidity_range db 25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55

CURR_TEMP db ?
CURR_HUMIDITY db ?
TEMP db ?
DAT2 DB 3 DUP(" ");
T DB 30H,31H

.CODE
.STARTUP

;INITIALIZE DS,SS,ES TO START OF RAM
MOV AX,08000H
MOV DS,AX
MOV SS,AX
MOV ES,AX
MOV SP,08FFEH

;INITIALIZING 8253
MOV AL,00010110B
OUT CREG,AL
MOV AL,5
OUT CNT0,AL

;INITIALIZING 8255(1)
MOV AL,10000000B 
OUT CREG1,AL
CALL DELAY_2MS

;INITIALIZING 8255(2)
MOV AL,10011010B 
OUT CREG2,AL
CALL DELAY_2MS

X1:
CALL FETCH_TEMP
MOV AL,CURR_TEMP
CALL FUNC
LEA SI,TEMP_RANGE
DEC SI
MOV CX,100

CALL DELAY
CALL DELAY
CALL DELAY

AGAIN:
INC SI
CMP [SI],AL
LOOPNE AGAIN

SUB SI,OFFSET TEMP_RANGE
LEA DI,HUMIDITY_RANGE
ADD DI,SI
MOV BL,[DI]

CALL FETCH_HUMIDITY
MOV AL,CURR_HUMIDITY
CALL FUNC
CMP BL,CURR_HUMIDITY
JAE X2
MOV AL,00001111B
OUT CREG1,AL      ;SWITCHES ON THE HUMIDIFIER(LED)


LOOP1:
CALL DELAY_2MS
CALL FETCH_HUMIDITY
CMP BL,CURR_HUMIDITY
JL LOOP1
MOV AL,00001110B
OUT CREG1,AL      ;SWITCHES OFF THE HUMIDIFIER(LED)

X2:
CALL DELAY_2MS
JMP X1

.EXIT

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;PROCEDURE TO FETCH CURRENT TEMPERATURE
FETCH_TEMP PROC NEAR

PUSH SI
;MOV AL,20H
;OUT PORT2A,AL

MOV AL,06H	;GIVE ADC	
OUT CREG2,AL

MOV AL,00H	;GIVE ALE
OUT CREG2,AL

MOV AL,02H	;GIVE SOC
OUT CREG2,AL

MOV AL,01H   ;SET ALE
OUT CREG2,AL

MOV AL,03H   ;SET SOC
OUT CREG2,AL

MOV AL,02H	;GIVE SOC
OUT CREG2,AL	

MOV AL,00H	;GIVE ALE
OUT CREG2,AL

LOOP2:
IN AL,PORT2C
CALL DELAY_2MS
AND AL,20H    ;CHECK FOR EOC    
CMP AL,20H
JNZ LOOP2
CALL DELAY_2MS

MOV AL,10011010B ;INITIALIZING 8255(2)
OUT CREG2,AL
IN AL,PORT2A ;AL HAS THE CURRENT TEMPERATURE

LEA SI,CURR_TEMP
MOV [SI],AL
POP SI
RET
FETCH_TEMP ENDP

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; PROCEDURE TO GET THE CURRENT HUMIDITY

FETCH_HUMIDITY PROC NEAR

PUSH SI

MOV AL,07H	;GIVE ADC	
OUT CREG2,AL

MOV AL,00H	;GIVE ALE
OUT CREG2,AL

MOV AL,02H	;GIVE SOC
OUT CREG2,AL

MOV AL,01H   ;SET ALE
OUT CREG2,AL

MOV AL,03H   ;SET SOC
OUT CREG2,AL

MOV AL,02H	;GIVE SOC
OUT CREG2,AL	

MOV AL,00H	;GIVE ALE
OUT CREG2,AL

LOOP2:
IN AL,PORT2C
CALL DELAY_2MS
AND AL,20H    ;CHECK FOR EOC    
CMP AL,20H
JNZ LOOP2
CALL DELAY_2MS

MOV AL,10011010B ;INITIALIZING 8255(2)
OUT CREG2,AL
IN AL,PORT2A ;AL HAS THE CURRENT HUMIDITY

LEA SI,CURR_HUMIDITY
MOV [SI],AL
POP SI
RET

FETCH_HUMIDITY ENDP

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

FUNC PROC NEAR
PUSH AX
PUSH BX
MOV AL,38H
CALL COMNDWRT
CALL DELAY
CALL DELAY
CALL DELAY
MOV AL,0EH
CALL COMNDWRT

MOV AL, 01  ;CLEAR LCD
CALL COMNDWRT
CALL DELAY
CALL DELAY

POP AX
PUSH AX
LEA DI,DAT2
MOV BX,100D
MOV DX,0
DIV BX
ADD AL,30H
CALL DATWRIT ;ISSUE IT TO LCD
CALL DELAY
CALL DELAY       
MOV AX,DX
MOV BX,10D 
MOV DX,0
DIV BX
ADD AL,30H
CALL DATWRIT
CALL DELAY
CALL DELAY
MOV AX,DX 
MOV DX,0
ADD AL,30H
CALL DATWRIT   
CALL DELAY
CALL DELAY
POP BX
POP AX

RET
FUNC ENDP

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

COMNDWRT PROC ;THIS PROCEDURE WRITES COMMANDS TO LCD
OUT PORT1B, AL  ;SEND THE CODE TO PORT B
MOV AL, 00000100B ;RS=0,R/W=0,E=1 FOR H-TO-L PULSE
OUT PORT1A, AL
NOP
NOP	
MOV AL, 00000000B ;RS=0,R/W=0,E=0 FOR H-TO-L PULSE
OUT PORT1A, AL
RET
COMNDWRT ENDP

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

DATWRIT PROC NEAR
	PUSH DX  ;SAVE DX 
	MOV DX,PORT1B  ;DX=PORT B ADDRESS
	OUT DX, AL ;ISSUE THE CHAR TO LCD
	MOV AL, 00000101B ;RS=1, R/W=0, E=1 FOR H-TO-L PULSE
	MOV DX, PORT1A ;PORT A ADDRESS
	OUT DX, AL  ;MAKE ENABLE HIGH
	MOV AL, 00000001B ;RS=1,R/W=0 AND E=0 FOR H-TO-L PULSE
	OUT DX, AL
	POP DX
	RET
DATWRIT ENDP ;WRITING ON THE LCD ENDS

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

DELAY_2MS PROC NEAR
MOV CX,100
HER: NOP
 LOOP HER
RET
DELAY_2MS ENDP

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

;DELAY IN THE CIRCUIT HERE THE DELAY OF 20 MILLISECOND IS PRODUCED
DELAY PROC
	MOV CX, 1325 ;1325*15.085 USEC = 20 MSEC
	W1: 
		NOP
		NOP
		NOP
		NOP
		NOP
	LOOP W1
	RET
DELAY ENDP 

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

DELAY_2S PROC
	MOV CX, 33125D 
	W2: 
		NOP
		NOP
		NOP
		NOP
		NOP
	LOOP W2
		MOV CX, 33125D 
	W3: 
		NOP
		NOP
		NOP
		NOP
		NOP
	LOOP W3
		MOV CX, 33125D 
	W4: 
		NOP
		NOP
		NOP
		NOP
		NOP
	LOOP W4
		MOV CX, 33125D 
	W5: 
		NOP
		NOP
		NOP
		NOP
		NOP
	LOOP W5
	RET
DELAY_2S ENDP

END